export default [
  {
    id: "000",
    name: "关于",
    page: "sys/about",
    icon: "icon-info",
    iconColor: "#ff74de",
    width: 600,
    height: 620,
    resizable: true,
  },
  {
    id: "001",
    name: "显示设置",
    page: "sys/display",
    icon: "icon-desktop",
    iconColor: "#328bfc",
    header: false,
    width: 600,
    height: 450,
    resizable: true,
  },
  {
    id: "002",
    name: "计算器",
    page: "sys/calculator",
    icon: "icon-percent",
    iconColor: "#F99408",
    header: true,
    width: 200,
    height: 362,
    resizable: true,
  },
  {
    id: "003",
    name: "浏览器",
    page: "sys/browser",
    icon: "icon-IE",
    iconColor: "#43A9E1",
    header: false,
    width: 1000,
    height: 600,
    resizable: true,
  },
  {
    id: "004",
    name: "灯光控制",
    page: "lightControl",
    icon: "icon-bulb",
    iconColor: "#FFCE54",
    header: false,
    width: 300,
    height: 500,
    resizable: false,
  },
  {
    id: "005",
    name: "矩阵LED",
    page: "matrixLED",
    icon: "icon-insertrowbelow",
    iconColor: "#6DFF06",
    header: true,
    width: 666,
    height: 298,
    resizable: true,
  },
  {
    id: "006",
    name: "终端",
    page: "sys/terminal",
    icon: "icon-codelibrary",
    iconColor: "#DBDBDB",
    header: true,
    width: 400,
    height: 300,
    resizable: true,
  },
  {
    id: "007",
    name: "分享",
    page: "share",
    icon: "icon-share-1",
    iconColor: "#AFFCFE",
    header: false,
    width: 1200,
    height: 600,
    resizable: true,
  },
  {
    id: "008",
    name: "预览",
    page: "preview",
    icon: "icon-View",
    iconColor: "#808BB5",
    header: false,
    width: 1200,
    height: 600,
    resizable: true,
  },
];
