/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FgImage: typeof import('./components/Fg/Image.vue')['default']
    FgInput: typeof import('./components/Fg/Input.vue')['default']
    FgSelect: typeof import('./components/Fg/Select.vue')['default']
    OSAPPLightControl: typeof import('./components/OS/APP/lightControl.vue')['default']
    OSAPPMatrixLED: typeof import('./components/OS/APP/matrixLED.vue')['default']
    OSAPPPreview: typeof import('./components/OS/APP/preview.vue')['default']
    OSAPPShare: typeof import('./components/OS/APP/share.vue')['default']
    OSAPPSysAbout: typeof import('./components/OS/APP/sys/about.vue')['default']
    OSAPPSysBrowser: typeof import('./components/OS/APP/sys/browser.vue')['default']
    OSAPPSysCalculator: typeof import('./components/OS/APP/sys/calculator.vue')['default']
    OSAPPSysDisplay: typeof import('./components/OS/APP/sys/display.vue')['default']
    OSAPPSysTerminal: typeof import('./components/OS/APP/sys/terminal.vue')['default']
    OSAPPSysTest: typeof import('./components/OS/APP/sys/test.vue')['default']
    OSCalendar: typeof import('./components/OS/Calendar.vue')['default']
    OSControl: typeof import('./components/OS/Control.vue')['default']
    OSDefaultWallpaper: typeof import('./components/OS/DefaultWallpaper.vue')['default']
    OSStart: typeof import('./components/OS/Start.vue')['default']
    OSWallpaper: typeof import('./components/OS/Wallpaper.vue')['default']
    OSWindow: typeof import('./components/OS/Window.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
